[env:seeed_xiao_nrf52840_sense]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840
framework = arduino
monitor_speed = 115200
lib_deps =
  https://github.com/Seeed-Studio/Seeed_Arduino_LSM6DS3.git
  https://github.com/sparkfun/SparkFun_AS7331_Arduino_Library.git
build_flags =
  -D SERIAL_LOG_BAUD=115200
